### ISSUE TITLE
Performance issues - batch processing

### ISSUE THREAD

**Issue by ph4r05** [wrangr/psl#11]
Hi!

Thanks for an awesome package I love it!

I wanted to use it in my dashboard project showing tens of certificates with tens to hundreds alternative domains - turned out the processing is just too slow :(

I also used lodash `_.memoize` function to tabulate the `get` method results but I am still on 13 seconds processing time on i7 proc.

I was wondering whether it could be possible to improve the search in the rule database as it seems to be the most expensive part.

It comes to my mind to somehow init the searching structure before use and then just use pre-processed rule database. E.g., the profiler shows `Punycode.toASCII` is quite expensive - 86.8% of the `get` processing time in the `findRule` method: 

```javascript
return internals.rules.reduce(function (memo, rule) {
    var punySuffix = Punycode.toASCII(rule.suffix);  // <--- overhead
    if (!internals.endsWith(punyDomain, '.' + punySuffix) && punyDomain !== punySuffix) {
      return memo;
    }
    // ...
}
```

The `Punycode.toASCII` call is called on static rules each time the `get` is called. PunySuffix could be pre-computed for static rules to optimize batch requests which saves a lot of time. Also the if condition can be swapped to firstly evaluate `punyDomain !== punySuffix`. If it fails the lazy evaluation skips the `endsWith` check. 

Profiler shows this is the critical path with significant overhead. There are also further improvements possible - e.g., to sort the database / build a suffix tree and reduce O(N) to O(lg(N)) where N is the database size. 

My profiller results:

total: 12963 ms
findrule: 12937 ms (99.8%)
findrule -> reduce: 12934 ms (99.8%)
toASCII: 11248 ms (86.8%)

just for illustration, without memoizing 993 domains took 15980 ms.

Pls let me know what you think about this improvement. I could also do a PR later if you let me know how do you like to have it implemented.

Thanks for considering!

**Comment by lupomontero** [comment]
Many thanks for the contribution. The PR has now been merged 🎉
