### ISSUE TITLE
SLD: "www" should fail on isValid

### ISSUE THREAD

**Issue by sashakirichek** [wrangr/psl#21]
Hello,

psl.isValid('www.co.uk') returns true but probably should not.
Seems like sld: 'www' should not be allowed?
https://jsfiddle.net/L4sv5pw6/2/ 

Thanks

**Comment by lupomontero** [comment]
Hi @sashakirichek,

Thanks for raising this issue.

This library (`psl`) parses domains based on the [Public Suffix List](https://publicsuffix.org/), and based on the definition of what this list is, when we parse `www.co.uk`, we get that `.co.uk` is a valid _public suffix_, but this doesn't necessarily mean that the _domain_ is valid, as in it being registrable or registered and resolving, it just says that _users_ can register domains at that particular _public suffix_. In this case, the domain `www.co.uk` is perfectly valid from the point of view of the public suffix, even if the domain itself does not work (it doesn't resolve), this is something specific to Nominet and not related the _public suffix_ itself.

For reference:

> A "public suffix" is one under which Internet users can (or historically could) directly register names. Some examples of public suffixes are .com, .co.uk and pvt.k12.ma.us. The Public Suffix List is a list of all known public suffixes.

Source: https://publicsuffix.org/

I hope this clarifies the library's behaviour.

Best,

L

**Comment by sashakirichek** [comment]
Got it. Thanks for clarification)

**Comment by lupomontero** [comment]
No probs ;-)

Closing this issue...
