### ISSUE TITLE
compared to parse-domain?

### ISSUE THREAD

**Issue by stevenvachon** [wrangr/psl#4]
[parse-domain](https://npmjs.com/parse-domain)

**Comment by lupomontero** [comment]
Hi @stevenvachon,

Apologies for the super delay in getting back to you.

I've had a quick look at `parse-domain` and it looks like it basically solves the same problem. I originally wrote this module a couple of years ago, when I needed it, and `parse-domain` was pretty "young" back then, so I decided to implement something similar to https://github.com/weppos/publicsuffix-ruby but for Node.js.

Best,

L
